import type { Metadata } from "next";
import localFont from "next/font/local";
import  "@smartleadmagnet/ui/globals.css";
import {LayoutProvider} from './context/LayoutContext'
import { Providers } from "./providers";


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#FCFCFC] dark:bg-black`}>
      <LayoutProvider>
      <Providers>
        {children}
      </Providers>
      </LayoutProvider>  
      </body>
    </html>
  );
}

